# Custom SSH configuration
Include ~/.config/ssh/local/*.conf

# 1Password SSH Agent
# DOC: https://www.1password.dev/ssh
Host *
    IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
